function assembleRow(name, regExp, goToUrl) {
    return '<tr>'
        + '<td><label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">'
        + '<input type="checkbox" id="checkbox-1" class="mdl-checkbox__input" checked>'
        + '</label></td>'
        + '<td style="width:40%;text-align:left">' + arguments[0] + '</td>'
        + '<td>|</td>'
        + '<td style="width:40%;text-align:left">' + arguments[1] + '</td>'
        + '<td>|</td>'
        + '<td style="width: 40%;text-align: left">' + arguments[3] + '</td>'
        + '<td><button class="mdl-button mdl-js-button mdl-button--icon">'
        + '<i class="material-icons">mood</i>'
        + '</button></td>'
        + '</tr>'
}
